### ISSUE TITLE
Fused multiply-subtract

### ISSUE THREAD

**Issue by GabrielMajeri** [rust-lang-nursery/packed_simd#111]
The `Simd` type does have a fused multiply-add function, but I was looking for the fused-multiply subtract function and couldn't find it. For AVX2, it's the equivalent of `_mm256_fmsub_ps` and similar.

**Comment by gnzlbg** [comment]
You can extend the `Simd` type yourself using `std::arch` in your own crates, or use a crate that does that like `faster`,`simdeez`, etc. The only intrinsics that we expose here are things that cannot be easily implemented on top of `std::arch`.  

I don't see any good reason to provide this, as in, LLVM / libmvec / SVML / ... do not provide a portable implementation of this operation that would be hard to implement otherwise.

**Comment by GabrielMajeri** [comment]
Thank you for your input. I discovered it's not necessary to use `_mm256_fmsub` anyway. Looking through the disassembly, it looks like LLVM automatically converts `x.fma(y, -z)` to the right fmsub instruction.

**Comment by gnzlbg** [comment]
Oh! that's great news. I think we should document that then, so I am re-opening this until we update the docs. Thanks!
