### ISSUE TITLE
Num traits

### ISSUE THREAD

**Issue by burrbull** [rust-lang-nursery/packed_simd#233]
Is implementation of [num_traits](https://rust-num.github.io/num/num_traits/index.html) in plans?

**Comment by gnzlbg** [comment]
It's not planed, I don't know how easy / hard would it be to do that. SIMD vectors do not implement `PartialOrd` but `num_traits` appears to require that.

**Comment by gnzlbg** [comment]
Why do you need this? 

I've thought a bit more about this and I don't think that this makes much sense (but please convince me otherwise). A `i32` is a `num::Int`, but 4 i32s (e.g. `(i32, i32, i32, i32)`, `[i32; 4]`, `[i32]`, `Vec<i32>`, ...) are not, so I don't think how one could implement the `num_traits` for these types.

If you wanted to be generic over vector types (or arrays, tuples, vecs, ...) you'd need different traits.

**Comment by burrbull** [comment]
I don't need this in fact. I just asked. Some math libraries use some of these traits. So... I just asked.

**Comment by gnzlbg** [comment]
Fair enough. If you end up needing these or figure a way how to implement them feel free to re-open.
