### ISSUE TITLE
`trunc` name is a bit confusing

### ISSUE THREAD

**Issue by pitdicker** [rust-lang-nursery/packed_simd#32]
See https://github.com/gnzlbg/packed_simd/pull/31#issuecomment-406871254.

`.trunc()` can be used to convert between types with the same number of lanes, but different integers sizes or floats. The name seems surprising to me. Maybe `.cast()` is an alternative?

**Comment by gnzlbg** [comment]
So what `trunc` actually does is a _numeric cast_ between vectors with the same number of lanes, such that:
 
* casting integer vectors whose lane types have the same size (e.g. i32xN -> u32xN) is a **no-op**
* casting from a larger integer to a smaller integer (e.g. u32xN -> u8xN) will **truncate**
* casting from a smaller integer to a larger integer (e.g. u8 -> u32) will
    * **zero-extend** if the source is unsigned or
    * **sign-extend** if the source is signed
* casting from a float to an integer will **round** the float towards zero (currently UB if the rounded value cannot be represented by the target integer type due to a bug)
* casting from an integer to float will produce the floating point representation of the integer, **rounded with an unspecified strategy** if necessary
* casting from an f32 to an f64 is perfect and lossless
* casting from an f64 to an f32 will **round with an unspecified strategy** to the closest possible value 

So `trunc` is obviously wrong. I would prefer to call this `.as()` but the name is probably reserved, so `.cast()` sounds fine to me. The `num` crate has a `NumCast` trait and a `cast` function, but it is not really documented which kinds of cast does that perform. 

The alternative would be to just provide the different methods: `.truncate()`, `.zero_extend()`, `.sign_extend()`, `.round(...)` - cc @rkruppe thoughts ?

**Comment by rkruppe** [comment]
I really don't want to wade into the bikeshed so I'm just going to throw out two hopefully uncontentious bullet points:

1. There's efforts underways to separate out the various kinds of casts that `as` can perform, see e.g. https://github.com/rust-lang/rfcs/pull/2484, vector types should be consistent with their scalar equivalents
2. Int->float and float->float casts aren't "rounded with an unspecified strategy" any more since LLVM cleaned up its act around its assumptions on the floating point environment -- see https://github.com/rust-lang-nursery/nomicon/pull/65

**Comment by gnzlbg** [comment]
@rkruppe thanks, I wasn't aware of RFC 2484.

@pitdicker I am currently renaming `trunc` to `cast`, and will commit that change. 

However, I will try to implement `TryFrom` and the other traits introduced in RFC2484. Once that is done, `.cast()` will be deprecated, and eventually removed, so consider `.cast()` as just a temporary workaround for migrating from `std::simd` until we have something better.

**Comment by pitdicker** [comment]
I am curious whether `TryFrom` can work with the same performance, but we'll see.

**Comment by gnzlbg** [comment]
I'm curious as well; no idea TBH.

**Comment by gnzlbg** [comment]
This is closed. The method is now named `cast`. I'll track implementing RFC2484 in a different issue.
